### ISSUE TITLE
Error wiith iTunes 12 and Macos Sierra

### ISSUE THREAD

**Issue by rcronald** [bendodson/Apple-TV-Alarm-Clock#1]
This issue appears when update to MacOs Sierra.

The error shows:
 error "System Events got an error: Can’t get menu \"Shuffle\" of menu item \"Shuffle\" of menu \"Controls\" of menu bar 1 of process \"iTunes\"." number -1728 from menu "Shuffle" of menu item "Shuffle" of menu "Controls" of menu bar 1 of process "iTunes"

I attach the error message:
![screen shot 2016-10-19 at 8 34 18 am](https://cloud.githubusercontent.com/assets/2396852/19520742/d9b3b658-95d6-11e6-9b00-da92d2675fb1.png)

**Comment by bendodson** [comment]
Fixed in commit 795f07c

(just need to change "of menu "Shuffle" of menu item" to "of menu 0 of menu item")
